### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Lonnycool3000** [Two-Play/Crafty-Discord-bot#2]
So, to help you a bit, idk if the m,istake is on my side or not but here is a quick copy paste of my bot who gets an error with the crafty commands like "list, start, stop" 

 2024-11-30 20:09:07 INFO     discord.client logging in using static token
 2024-11-30 20:09:08 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: ec91a0e9ca8b79d541cf0c172f0a24eb).
 Bot is ready. Renny_Bot#2168
 Crafty Bot version 0.1.1
 Server URL: 192.168.2.188:8443
 GUILD ID: 1306542177492402247
 auto stop disabled
 commands
 servers
 2024-11-30 20:10:57 ERROR    discord.client Ignoring exception in on_command_error
 Traceback (most recent call last):
   File "/usr/local/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
     await coro(*args, **kwargs)
   File "/usr/src/app/./core/main.py", line 272, in on_command_error
     if isinstance(error, commands.CommandNotFound):
                          ^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'HybridCommand' object has no attribute 'CommandNotFound'
 sync
 servers
 2024-11-30 20:11:33 ERROR    discord.client Ignoring exception in on_command_error
 Traceback (most recent call last):
   File "/usr/local/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
     await coro(*args, **kwargs)
   File "/usr/src/app/./core/main.py", line 272, in on_command_error
     if isinstance(error, commands.CommandNotFound):
                          ^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'HybridCommand' object has no attribute 'CommandNotFound'
 start

**Comment by Two-Play** [comment]
Thank you very much!
And sorry for the mistake with the clean/clear command.
Yes, the slash commands are buggy, and I don’t really understand them either. Maybe try restarting the bot and using only >sync 2–3 times if necessary. It should sync 9 commands at this point. The clear command causes more problems than it solves.
